apiVersion: skaffold/v4beta1
kind: Config
build:
  artifacts:
    - image: omotomiwa/auth-service
      context: auth
      sync:
        manual:
          - src: src/**
            dest: .
      docker:
        dockerfile: Dockerfile
  googleCloudBuild:
    projectId: filmonk-app
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
