apiVersion: skaffold/v4beta1
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
# deploy:
#   kubectl:
#     manifests:
#       - ./infra/k8s/*
build:
  artifacts:
    - image: omotomiwa/auth
      context: auth
      sync:
        manual:
          - src: src/**
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: omotomiwa/client
      context: client
      sync:
        manual:
          - src: src/**
            dest: .
      docker:
        dockerfile: Dockerfile
  # googleCloudBuild:
  #   projectId: filmonk-app
# deploy:
#   kubectl: {}
