apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-postgres-secret
  labels:
    app: auth-postgres
data:
  POSTGRES_DB: appdb
  POSTGRES_USER: appuser
  POSTGRES_PASSWORD: strongpasswordapp
